services:

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: SafeSurf-AI-frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./assets:/app/assets
    working_dir: /app
    command: npm start
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - safesurf_net

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: SafeSurf-AI-backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./assets:/app/assets
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ALLOW_ORIGINS=http://localhost:3000
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=False
    depends_on:
      - db
    networks:
      - safesurf_net

  db:
    image: postgres:14
    container_name: safesurf-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - safesurf_net

  nginx:
    image: nginx:latest
    container_name: safesurf-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - safesurf_net

volumes:
  postgres-data:

networks:
  safesurf_net:
